name: Build and Deploy Webassembly Project
on: [push, workflow_dispatch]

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@29ba4851d6da084ffdc1e0fc390efadbd75df9d1 # point to v11
        with:
          # Version to install
          version: latest # optional, default is latest
          
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build_webasm -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DPLATFORM=Web

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build_webasm
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: '${{github.workspace}}/build_webasm/bin'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
